---
- name: "Create a dedicated admin user and group"
  hosts: "{{ host }}"
  tasks:
  - name: Create a dedicated admin group
    group:
      name: "{{ flix_admin_group }}"
      state: present

  - name: Create a dedicated admin user
    user:
      name: "{{ flix_admin }}"
      password: "{{ flix_admin_pass | password_hash('sha512', password_salt) }}"
      group: "{{ flix_admin_group }}"
      shell: /bin/bash
      create_home: yes

- name: "Deploy Dockerized OTTServer"
  gather_facts: yes
  hosts: "{{ host }}"
  become: yes
  become_user: root
  roles:
    - setup_dependencies
    - setup_scripts
    - spin_up_docker