- name: "Copy the SQL startup script to MariaDB Dockerfile location"
  copy:
    src: /var/www/html/src/SQL_template/modak_flix.sql
    dest: ../../../mariadb/
    mode: "0644"
    remote_src: yes

- name: "Copy the album_art.jpg from Venom movie to cached_images"
  copy:
    src: "/var/www/html/src/Movies/Venom (2018)/album_art.jpg"
    dest: "/var/www/html/src/cached_images/Venom (2018)_album_art.jpg"
    mode: "0644"
    remote_src: yes

- name: "Copy the dp.php script to hosted directory"
  copy:
    src: ../templates/db.php
    dest: /var/www/html/src/db.php
    mode: "0644"
    remote_src: yes

- name: "Copy the path.php script to hosted directory"
  copy:
    src: ../templates/path.php
    dest: /var/www/html/src/path.php
    mode: "0644"
    remote_src: yes
