- name: "Download Git repo"
  git:
    repo: https://github.com/official-srv-modak/OTTServer.git
    dest: /var/www/html/src/
    version: main
    force: yes

- name: "Install docker-compose"
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system }}-{{ ansible_machine }}"
    dest: /usr/local/bin/docker-compose
    mode: "0755"