- name: "Pull the docker-compose file from templates"
  copy:
    src: "./templates/docker-compose.yml.j2"
    dest: "./docker-compose.yml"
    mode: "0644"
    remote_src: yes

- name: "Execute the docker-compose file"
  docker_compose:
    project_src: "./"
  vars:
    ansible_python_interpreter: /bin/python3
  register: docker_compose_output

- name: "Print the output of docker-compose up"
  debug:
    msg: "{{  docker_compose_output  }}"