- name: "Install MariaDB server"
  package:
    name: mariadb-server
    state: present

- name: "Start MariaDB service"
  become: yes
  become_user: "{{ flix_admin }}"
  service:
    name: mariadb
    state: started

- name: "Create database"
  mysql_db:
    name: "{{ mysql_db }}"
    config_file: /etc/my.cnf
    login_unix_socket: /var/lib/mysql/mysql.sock
    state: present

- name: "Create a user for the database"
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "*.*:ALL"
    state: present