- name: "Install MariaDB server"
  become: yes
  become_user: root
  package:
    name: mariadb-server
    state: present

- name: "Start MariaDB service"
  service:
    name: mariadb
    enabled: yes
    state: started

- name: "Create database"
  mysql_db:
    name: "{{ mysql_db }}"
    config_file: /etc/my.cnf
    login_unix_socket: /var/lib/mysql/mysql.sock
    state: present

- name: "Create a user for the database"
  no_log: yes
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "*.*:ALL"
    state: present