---
- name: "Install firewall daemon"
  package:
    name: firewalld
    state: present

- name: "Start firewall service"
  service:
    name: firewalld
    enabled: yes
    state: started

- name: "Permit traffic on default port for MariaDB through firewall"
  firewalld:
    port: 3000-3005/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: "Permit traffic on default port for httpd through firewall"
  firewalld:
    port: 8000-8005/tcp
    permanent: yes
    state: enabled
    immediate: yes